### PR TITLE
Add missing TransferInPlace for 0.6.1

### PR DESCRIPTION
**Pull request by fenax**
Hello, I needed a library that required this trait to be implemented
So here it is, It is tiny and mostly a copy of the Transfer trait implementation.

### CODE REVIEW

**Review by ryankurte — APPROVED** [review]
looks great, though there seems to be a merge conflict?

**Comment by fenax** [comment]
Not sure how I should send the pull request as it is based on 0.6.1 but the conflicts is with the current status of main branch, which doesn't need it.

**Comment by fenax** [comment]
I see two possibilities:
I am no git expert though so I could be mistaken

1. 
you create a branch from tag 0.6.1
I submit my pull request against that branch
you tag 0.6.2 for example from that branch

2.
I submit the pull request from the current state of the main branch
you tag the after the merge
you revert my changes, bringing main back to its current state

**Comment by ryankurte** [comment]
ahh, thanks i had not clicked that this was 0.6.1 vs. 0.7.0 now, running a `v0.6.x` branch from `v0.6.1` is a good approach, and any other fixes can be backported and released from there.

**Comment by ryankurte** [comment]
should be released in `0.6.2`, please do lmk how it goes ^_^

**Pull request merged**
