### PR TITLE
wip: Add 1.0.0-alpha.8 -> 0.2.7 compat layer

### LINKED ISSUE #9: Support 1.0.0-alpha.8
I'm going to have a go at this, but don't want to duplicate effort if you've already got something in the works.

### PR DESCRIPTION
**Pull request by nathaniel-brough**
Closes ryankurte/embedded-hal-compat#9

**TODO**:
- [x] Update to new traits
- [x] Get new compat layer building
- [x] Implement new compat layer 
- [ ] Update docs/tests and ensure passing/building

### CODE REVIEW

**Comment by har7an** [comment]
Hi there,

may/shall I lend a hand in implementing this, maybe? I'm trying to bump `rust-radio-sx128x` to `1.0.0-alpha8`, and it depends on this crate via a whole bunch of intermediary crates, so I'm very interested in having this available upstream.

**Comment by nathaniel-brough** [comment]
Yeah, I'd be glad for the help. I've had other priorities pop up and probably won't get back to this for another week or two.

Feel free to fork my repo and have a go at it. I'm not sure how it'd go logistically with a fork of a fork. If there is anything that you have questions about, feel free to tag me.

**Comment by nathaniel-brough** [comment]
Thanks to @har7an this is now ready to merge. There are still some issues with the doctests (which seemed to be broken before I started this PR) I've opened issue #11 to track that.

**Comment by ryankurte** [comment]
lgtm, thanks for all your efforts! once we've fixed #11 i'll tag a release

**Pull request merged**
