### PR TITLE
prep for release v0.13.0

### PR DESCRIPTION
**Pull request by ryankurte**
following up #34

### CODE REVIEW

**Review by eldruin — COMMENTED** [review]
Thanks!
Could you update the changelog as well?

**Review by eldruin — COMMENTED** [review]
Thanks! Could you add/update the links for `[0.13.0]`?

**Comment by ryankurte** [comment]
good catch! it's been a minute since i last did this 😅

**Review by eldruin — APPROVED** [review]
Looks good to me, thank you!

**Pull request merged**
