### PR TITLE
wip: Update to embedded-hal v1.0

### PR DESCRIPTION
**Pull request by Dirbaio**
I'm not sure how to handle `Reverse` for `InputPin`: the 0.2 traits only give us `&self`, but the 1.0 traits require `&mut self`.

Maybe we can not implement `InputPin` on `Reverse<T>`, and and add a second set of mpls on `Reverse<RefCell<T>>` which does impl `InputPin`??

### CODE REVIEW

**Comment by MabezDev** [comment]
> Maybe we can not implement InputPin on Reverse<T>, and and add a second set of mpls on Reverse<RefCell<T>> which does impl InputPin??

Hmm, this seems like the only way. At least I can't think of another. The trait has changed in a fundamentally breaking way, so we can only resort to interior mutability now.

**Comment by dimpolo** [comment]
Would be nice to get this :)

**Comment by blaine** [comment]
Seconding! 😊 I'm trying to use a 0.2.x driver that's not likely to get 1.0 compat soon, and I would extremely love to not have to add that support right now. :D

**Comment by Dirbaio** [comment]
closing in favor of #34

**Pull request closed without merging**
